### PR TITLE
Updated to node 12.x

### PR DESCRIPTION
**Pull request by jonahharris**

### CODE REVIEW

**Comment by jonahharris** [comment]
@btrask my similar v12 support changes for node-pcap, which this is an underlying module for, are about to be committed. Preferably, it would be good to continue for it to be based it based on this repo instead of my fork. Are you still maintaining it?

**Comment by moznion** [comment]
Our organization is in trouble with what installation of node_pcap and this library has been failing on node v12 environment. It seems node_pcap side is ready to support node v12, however, the current status of this library could be a blocker for that.
I really hope this patch was merged and it'll be published.

**Comment by HLeithner** [comment]
@btrask it would be really great if you can merge this PR and release a new version.

**Comment by aalwash** [comment]
Can someone please approve this PR?

**Comment by btrask** [comment]
Sorry everyone I was dead for a while.

I'd like to push this patch to npm, but I don't own the package there anymore. @jonahharris do you want to either publish an update or [add me as a maintainer](https://docs.npmjs.com/transferring-a-package-from-a-user-account-to-another-user-account) again?

**Comment by jonahharris** [comment]
@btrask you've been added back as the maintainer - it's your baby :)

**Comment by btrask** [comment]
@jonahharris Thank you! I've added you as a collaborator to this repo, too.

@aalwash: I pushed 0.4.0 to npm. Let me know how it goes!

**Comment by aalwash** [comment]
Thanks @btrask , tested with node12 and it works!

Now I need to kick someone from node-red-contrib-pcap to updated their dependencies ;)

**Comment by btrask** [comment]
Good to hear it @aalwash. Thanks to @jonahharris for doing all the hard work!

**Pull request merged**
